[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mead-tools"
version = "0.1"
description = "Tools for mead and wine calculations."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "typer>=0.12,<1.0"
]

[project.scripts]
mead = "mead_tools.main:app"

[tool.setuptools.package-data]
mead_tools = ["data/*.json"]
